TYPE=VIEW
query=select `p`.`id_punto` AS `id_punto`,`p`.`identificativo_fisico` AS `identificativo_fisico`,`p`.`tipo_veicolo` AS `tipo_veicolo`,`p`.`tipo_connettore` AS `tipo_connettore`,`p`.`potenza_max_kw` AS `potenza_max_kw`,`p`.`tariffa_predefinita` AS `tariffa_predefinita`,`s`.`id_stazione` AS `id_stazione`,`s`.`nome` AS `nome_stazione`,`s`.`latitudine` AS `latitudine`,`s`.`longitudine` AS `longitudine`,`s`.`indirizzo` AS `indirizzo`,case when `p`.`stato_hardware` in (\'guasto\',\'manutenzione_programmata\') then \'fuori_servizio\' when `p`.`data_ultimo_heartbeat` is null then \'offline\' when `p`.`data_ultimo_heartbeat` < current_timestamp() - interval 5 minute then \'offline\' when `sess`.`id_sessione` is not null then \'occupata\' else \'libera\' end AS `stato_calcolato`,`sess`.`id_sessione` AS `id_sessione`,`sess`.`data_inizio` AS `occupata_da`,timestampdiff(MINUTE,`sess`.`data_inizio`,current_timestamp()) AS `minuti_trascorsi`,`u`.`nome` AS `occupante_nome`,`u`.`cognome` AS `occupante_cognome`,`acc`.`percentuale_carica` AS `batteria_stazione_perc`,`acc`.`livello_corrente_kwh` AS `batteria_stazione_kwh`,`acc`.`stato_operativo` AS `batteria_stato` from ((((`db_green_school`.`punti_ricarica` `p` join `db_green_school`.`stazioni` `s` on(`p`.`id_stazione` = `s`.`id_stazione`)) left join `db_green_school`.`sessioni_ricarica` `sess` on(`p`.`id_punto` = `sess`.`id_punto` and `sess`.`data_fine` is null)) left join `db_green_school`.`utenti` `u` on(`sess`.`id_utente` = `u`.`id_utente`)) left join `db_green_school`.`accumulatori_stazione` `acc` on(`s`.`id_stazione` = `acc`.`id_stazione`))
md5=676d9cfe7e3ec315c3e7b5339cf1468e
updatable=0
algorithm=0
definer_user=admin
definer_host=%
suid=2
with_check_option=0
timestamp=0001776271873507140
create-version=2
source=SELECT\n    p.id_punto,\n    p.identificativo_fisico,\n    p.tipo_veicolo,\n    p.tipo_connettore,\n    p.potenza_max_kw,\n    p.tariffa_predefinita,\n    s.id_stazione,\n    s.nome AS nome_stazione,\n    s.latitudine,\n    s.longitudine,\n    s.indirizzo,\n    CASE\n        WHEN p.stato_hardware IN (\'guasto\', \'manutenzione_programmata\') THEN \'fuori_servizio\'\n        WHEN p.data_ultimo_heartbeat IS NULL THEN \'offline\'\n        WHEN p.data_ultimo_heartbeat < (NOW() - INTERVAL 5 MINUTE) THEN \'offline\'\n        WHEN sess.id_sessione IS NOT NULL THEN \'occupata\'\n        ELSE \'libera\'\n    END AS stato_calcolato,\n    sess.id_sessione,\n    sess.data_inizio AS occupata_da,\n    TIMESTAMPDIFF(MINUTE, sess.data_inizio, NOW()) AS minuti_trascorsi,\n    u.nome AS occupante_nome,\n    u.cognome AS occupante_cognome,\n    acc.percentuale_carica AS batteria_stazione_perc,\n    acc.livello_corrente_kwh AS batteria_stazione_kwh,\n    acc.stato_operativo AS batteria_stato\nFROM punti_ricarica p\nINNER JOIN stazioni s ON p.id_stazione = s.id_stazione\nLEFT JOIN sessioni_ricarica sess ON p.id_punto = sess.id_punto AND sess.data_fine IS NULL\nLEFT JOIN utenti u ON sess.id_utente = u.id_utente\nLEFT JOIN accumulatori_stazione acc ON s.id_stazione = acc.id_stazione
client_cs_name=utf8mb3
connection_cl_name=utf8mb3_general_ci
view_body_utf8=select `p`.`id_punto` AS `id_punto`,`p`.`identificativo_fisico` AS `identificativo_fisico`,`p`.`tipo_veicolo` AS `tipo_veicolo`,`p`.`tipo_connettore` AS `tipo_connettore`,`p`.`potenza_max_kw` AS `potenza_max_kw`,`p`.`tariffa_predefinita` AS `tariffa_predefinita`,`s`.`id_stazione` AS `id_stazione`,`s`.`nome` AS `nome_stazione`,`s`.`latitudine` AS `latitudine`,`s`.`longitudine` AS `longitudine`,`s`.`indirizzo` AS `indirizzo`,case when `p`.`stato_hardware` in (\'guasto\',\'manutenzione_programmata\') then \'fuori_servizio\' when `p`.`data_ultimo_heartbeat` is null then \'offline\' when `p`.`data_ultimo_heartbeat` < current_timestamp() - interval 5 minute then \'offline\' when `sess`.`id_sessione` is not null then \'occupata\' else \'libera\' end AS `stato_calcolato`,`sess`.`id_sessione` AS `id_sessione`,`sess`.`data_inizio` AS `occupata_da`,timestampdiff(MINUTE,`sess`.`data_inizio`,current_timestamp()) AS `minuti_trascorsi`,`u`.`nome` AS `occupante_nome`,`u`.`cognome` AS `occupante_cognome`,`acc`.`percentuale_carica` AS `batteria_stazione_perc`,`acc`.`livello_corrente_kwh` AS `batteria_stazione_kwh`,`acc`.`stato_operativo` AS `batteria_stato` from ((((`db_green_school`.`punti_ricarica` `p` join `db_green_school`.`stazioni` `s` on(`p`.`id_stazione` = `s`.`id_stazione`)) left join `db_green_school`.`sessioni_ricarica` `sess` on(`p`.`id_punto` = `sess`.`id_punto` and `sess`.`data_fine` is null)) left join `db_green_school`.`utenti` `u` on(`sess`.`id_utente` = `u`.`id_utente`)) left join `db_green_school`.`accumulatori_stazione` `acc` on(`s`.`id_stazione` = `acc`.`id_stazione`))
mariadb-version=101116
