# Listener standard per sensori e simulatore Python
listener 1883 0.0.0.0
protocol mqtt

# Listener per Dashboard Web (WebSockets)
listener 9001 0.0.0.0
protocol websockets

# Sicurezza
#allow_anonymous false
#password_file /mosquitto/config/password_file